### ISSUE TITLE
Couldn't attend call

### ISSUE THREAD

**Issue by fazilcdev** [MrHertal/react-native-twilio-phone#35]
I was tested my Twilio app in multiple android devices (versions >= 8). But it's not working in some devices. I have 2 issues
1- Sometimes call not ringing in some particular device
2- Sometimes couldn't attend call

Nb: I was integrated Twilio phone client as task router worker. In Twilio dashboard tasks assigned and reserved without any problem. But in some devices call rings multiple times or couldn't attend call or sometimes call not ringing. I attaching a video.
https://youtu.be/pDqTOO8oJWk

React.useEffect(() => {
    return RNTwilioPhone.initialize(callKeepOptions, fetchAccessToken, options);
  }, []); // in my home.js

RNTwilioPhone.handleBackgroundState(); //in my index.android.js

Can you please help to figure out this issue

Thank you

**Comment by MrHertal** [comment]
Hi, it looks weird.

Make sure to install react-native-callkeep@4.0.1 and react-native-voip-push-notification@3.1.0 because I did not test the very last versions of those libraries.

Then in order to solve your issue, you can build and run the [example app](https://github.com/MrHertal/react-native-twilio-phone#example-app) and try to figure out what's the difference between the example app configuration and your app.
