### ISSUE TITLE
Call received when app is killed/terminated, but not connected to the call

### ISSUE THREAD

**Issue by mohsinayoob** [MrHertal/react-native-twilio-phone#36]
Hi,
I am using this package for client to client call in react native (iOS) app. Everything is working fine but there is some issue when app is killed or terminated.
Here are the scenarios:
**Cases:** 
-> Seconds are not incrementing in native call UI
Received VOIP PUSH -> Incoming Call displayed with as expected -> Immediately answered the call -> call was not connected the other end -> On receiver side ring was stopped and seconds are not incrementing but on caller side it was in ringing state. (Looks like JS bundle was not loaded)
-> Received VOIP PUSH -> Incoming Call displayed with as expected -> Waited to load JS bundle and then answered the call -> call was not connected the other end -> On receiver side seconds are incrementing but on caller side it was in ringing state. 
CallConnected event was not triggered in both cases. 

facing same issue (in foreground and background) when use `RNTwilioPhone.initializeCallKeep(callKeepOptions, this.fetchAccessToken);` instead of `RNTwilioPhone.initialize(callKeepOptions, this.fetchAccessToken);`

Everything is working fine when the app is in background or foreground state.

**Comment by MrHertal** [comment]
Hi @mohsinayoob,

Make sure to install react-native-callkeep@4.0.1 and react-native-voip-push-notification@3.1.0 because I did not test the very last versions of those libraries.

Then in order to solve your issue, you can build and run the [example app](https://github.com/MrHertal/react-native-twilio-phone#example-app) and tell me if you can reproduce the bug on your device. If you cannot reproduce, we should look for any differences between your app and the example app.

Thanks.

**Comment by heyalexchoi** [comment]
Seeing similar issues. Downgraded to  react-native-callkeep@4.0.1 and react-native-voip-push-notification@3.1.0. Still seeing issue. Am seeing Callkeep's `answerCall` event firing but RNTwilioPhone `CallConnected` is not firing. Currently working through issue.

UPDATE:
removed `[RNVoipPushNotificationManager voipRegistration];` from app delegate's `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` and that fixed my issue.
