### ISSUE TITLE
Multiple incoming calls

### ISSUE THREAD

**Issue by josaric** [MrHertal/react-native-twilio-phone#50]
Hi, is it possible to register incoming calls for multiple Twilio accounts?
I have two Twilio accounts and I want to enable receive calls from both numbers, but that means that:

`RNTwilioPhone.initialize(callKeepOptions, this.fetchAccessToken);`

should be initialised twice, once for each account with different access token.

**Comment by MrHertal** [comment]
Hi,

`RNTwilioPhone` was designed to use only one `fetchAccessToken` callback, as you can see [here](https://github.com/MrHertal/react-native-twilio-phone/blob/master/src/RNTwilioPhone.ts#L72).

I have never tried to use two different Twilio accounts, so I don't know if it's possible. But I guess you will have to rewrite `RNTwilioPhone` class in order to implement your own logic and call the [low level API method](https://github.com/MrHertal/react-native-twilio-phone#low-level-api) `register` twice.
