### ISSUE TITLE
What is the significance of access token in this example? How can I call one device to another using the example application?

### ISSUE THREAD

**Issue by subinsuresh991** [MrHertal/react-native-twilio-phone#7]

**Comment by MrHertal** [comment]
Hi,

The access token is a JWT token that contains the identity of your client and is used to register a device to Twilio.
It must be generated on your side. Twilio provides some [starter projects](https://www.twilio.com/docs/voice/voip-sdk/ios/get-started#3-configure-a-server-to-generate-an-access-token-to-be-used-in-the-app) that show how to generate that token.

`RNTwilioPhone` takes an async function as argument that returns the access token. It does not take the token directly as an argument because it needs to fetch a fresh token when making calls.

In order to make a client-to-client call with the example app, you need first to install it on two real devices.

On the first device, you fetch the access token using one identity (Larry for example).
On the second device, you fetch the access token using another identity (like Steve).

Note that you could register with the same identity, if you want to receive a call on both devices.

Then you can make Larry call Steve. Here is the result in Twilio console:

<img width="1155" alt="99179849-927cf980-2721-11eb-9730-7f7576585eed" src="https://user-images.githubusercontent.com/11944221/99943733-0cd8f980-2d72-11eb-8d45-0d1e99fd3565.png">

**Comment by akshitrcrm** [comment]
@MrHertal I had few questions.
My usecase is only to make outgoing calls so I did `return RNTwilioPhone.initializeCallKeep`
with the options and i am able to make. call from an android device . But on iOS call is made but the native calling screen does not show up. i followed every step in callkeep still dont know why.

Another thing is i explored your code and saw that you already start listening to the callkeep and twilio listeners once i call initialize but when i startCall, and when callConnected is fired, i still get an empty array when i say RNTwilioPhone.calls,
and when i tap the end call button from native UI it doesnt end the call just closes the UI. Same if we end call from other device. nothing happens. so then i myself added listeners by importing the twilioPhoneEmitter but now i cant get uuid or sid wherever i need to use the low level functions from TwilioPhone.
The rest of the methods and variables you have set private so i cant access them like if i want to know the sid or uuid outside of the listeners how do i do that?

**Comment by MrHertal** [comment]
Hi @akshitrcrm,

> My usecase is only to make outgoing calls so I did return RNTwilioPhone.initializeCallKeep
with the options and i am able to make. call from an android device . But on iOS call is made but the native calling screen does not show up. i followed every step in callkeep still dont know why.

It's normal, there seems to be no way to display iOS UI when starting an outgoing call. I invite you to check CallKeep issues for more details. The iOS UI is only displaying when receiving incoming calls. You will have to build your own UI by retrieving current call with `RNTwilioPhone.calls` and calling [TwilioPhone API](https://github.com/MrHertal/react-native-twilio-phone#low-level-api).

> Another thing is i explored your code and saw that you already start listening to the callkeep and twilio listeners once i call initialize but when i startCall, and when callConnected is fired, i still get an empty array when i say RNTwilioPhone.calls,
and when i tap the end call button from native UI it doesnt end the call just closes the UI. Same if we end call from other device. nothing happens. so then i myself added listeners by importing the twilioPhoneEmitter but now i cant get uuid or sid wherever i need to use the low level functions from TwilioPhone.

Sorry for the issue.
I recently made a fix regarding this problem, please upgrade to last version: https://github.com/MrHertal/react-native-twilio-phone/releases/tag/v1.3.2

Tell me if you still have this issue after that.
