### ISSUE TITLE
Emergency help. SIGABRT: __NSCFNumber > Could not cast value of type '__NSCFNumber' (0x1f1c58d28) to 'NSString' (0x1f1c58cf8).  > NSString

### ISSUE THREAD

**Issue by duypxd** [MrHertal/react-native-twilio-phone#72]
We got this error 3 days ago. Our app is working normally in prod so far and no new updates. @MrHertal  :( 

`SIGABRT: __NSCFNumber > Could not cast value of type '__NSCFNumber' (0x1f1c58d28) to 'NSString' (0x1f1c58cf8).
 > NSString`

**Comment by jorgeavaldez** [comment]
Same here

**Comment by therealemjy** [comment]
Same thing happening with our app.

**Comment by jorgeavaldez** [comment]
Broke in our app in production, just checked. After digging through the internals, one thing that stands out is that the PKPushPayload includes a number value under a timeout key. By the time it crashes, it's trying to dispatch the received payload from Twilio in our case back to TwilioPhone.

**Comment by dchannell** [comment]
Same here. App immediately crashes on incoming calls. It seems to be something related to the handling of the Voip Push Notification and serializing the push payload data.  

The culprit seems to be related with:
```
[RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:[NSString stringWithFormat:@"%@", type]];
```

Note: I noticed that the only value in the payload that is of type `__NSCFNumber` is the `twi_timeout` property.

**Comment by duypxd** [comment]
This is not a good firecracker solution. But it works fine for me. cc: @MrHertal 


![image](https://user-images.githubusercontent.com/31473225/145505584-c56e9dc0-f4c9-41af-baa5-e04739eecf2d.png)

**Comment by MrHertal** [comment]
Thanks to all of you for reporting this nasty bug.

I am currently working on a fix.

**Comment by MrHertal** [comment]
This should work now with v1.8.1 (see https://github.com/MrHertal/react-native-twilio-phone/pull/74)

The bug was due to the fact that in its incoming push, Twilio sends a `twi_answer_timeout` field as an integer but the module code was expecting a string ... while on the Android side,`twi_answer_timeout` is indeed a string 😭

**Comment by duypxd** [comment]
Thanks so much for the support. @MrHertal 🏆

**Comment by therealemjy** [comment]
Thanks for the quick update! Much appreciated.

**Comment by manjotssd** [comment]
thank you for quick fix @MrHertal
